name: VPS Deployment

on:
  push:
    branches:
      - main # Define the branch to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest # Use Ubuntu as the runner environment

    steps:
      - name: Echo
        run: |
          echo ${{ vars.VPS_HOST }}
          echo ${{ vars.VPS_USERNAME }}
          # echo ${{ vars.VPS_PASSWORD }}  # Assuming SSH key authentication, no password needed

      - name: Checkout Repository
        uses: actions/checkout@v2 # Check out the repository content

      - name: SSH and Copy Files to VPS
        uses: appleboy/ssh-action@v2
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Use GitHub secret containing SSH private key
          port: 22
          script: |
            mkdir -p ${{ vars.VPS_WORKDIR }}
            rsync -avz --exclude='.git/' ./ ${{ vars.VPS_USERNAME }}@${{ vars.VPS_HOST }}:${{ vars.VPS_WORKDIR }}

      - name: Build Docker Image
        run: |
          docker build -t iris-mlops .  # Build Docker image from the copied files

      - name: Run Docker Container
        run: |
          docker run -d --name iris-mlops -p 8000:80 iris-mlops
