name: VPS Deployment

on:
  push:
    branches:
      - main # Define the branch to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest # Use Ubuntu as the runner varsironment

    steps:
      - name: Echo
        run: |
          echo ${{ vars.VPS_HOST }}
          echo ${{ vars.VPS_USERNAME }}
          echo ${{ vars.VPS_PASSWORD }}
      - name: Checkout Repository
        uses: actions/checkout@v4 # Check out the repository content

      - name: SSH into VPS and Copy Files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VPS_HOST }} # Set your VPS host as a GitHub secret
          username: ${{ vars.VPS_USERNAME }} # Set your VPS username as a GitHub secret
          password: ${{ vars.VPS_PASSWORD }} # Set your VPS password as a GitHub secret
          script: |
            mkdir -p {{vars.WORKDIR}}  # Create a directory on VPS
            scp -r ./* ${{ vars.VPS_USERNAME }}@${{ vars.VPS_HOST }}:${{ vars.WORKDIR }}  # Copy repository files to VPS

      - name: Build Docker Image
        run: |
          docker build -t iris-mlops .  # Build Docker image from the copied files

      - name: Run Docker Container
        run: |
          docker run -d --name iris-mlops -p 8080:80 iris-mlops  # Run Docker container from the built image
